// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: snowflake.proto

/*
Package platform_id_srv_snowflake is a generated protocol buffer package.

It is generated from these files:
	snowflake.proto

It has these top-level messages:
	GetIDReq
	GetIDResp
*/
package platform_id_srv_snowflake

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SnowFlake service

type SnowFlakeService interface {
	GetID(ctx context.Context, in *GetIDReq, opts ...client.CallOption) (*GetIDResp, error)
}

type snowFlakeService struct {
	c    client.Client
	name string
}

func NewSnowFlakeService(name string, c client.Client) SnowFlakeService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "platform.id.srv.snowflake"
	}
	return &snowFlakeService{
		c:    c,
		name: name,
	}
}

func (c *snowFlakeService) GetID(ctx context.Context, in *GetIDReq, opts ...client.CallOption) (*GetIDResp, error) {
	req := c.c.NewRequest(c.name, "SnowFlake.GetID", in)
	out := new(GetIDResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SnowFlake service

type SnowFlakeHandler interface {
	GetID(context.Context, *GetIDReq, *GetIDResp) error
}

func RegisterSnowFlakeHandler(s server.Server, hdlr SnowFlakeHandler, opts ...server.HandlerOption) error {
	type snowFlake interface {
		GetID(ctx context.Context, in *GetIDReq, out *GetIDResp) error
	}
	type SnowFlake struct {
		snowFlake
	}
	h := &snowFlakeHandler{hdlr}
	return s.Handle(s.NewHandler(&SnowFlake{h}, opts...))
}

type snowFlakeHandler struct {
	SnowFlakeHandler
}

func (h *snowFlakeHandler) GetID(ctx context.Context, in *GetIDReq, out *GetIDResp) error {
	return h.SnowFlakeHandler.GetID(ctx, in, out)
}
