// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package platform_user_srv_info

import (
	fmt "fmt"
	idl "github.com/dy-platform/user-api-passport/idl"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//获取用户信息请求参数
type GetUserInfoReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	AttrNameList         []string `protobuf:"bytes,2,rep,name=AttrNameList,proto3" json:"AttrNameList,omitempty"`
	AppId                int32    `protobuf:"varint,3,opt,name=AppId,proto3" json:"AppId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{0}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserInfoReq) GetAttrNameList() []string {
	if m != nil {
		return m.AttrNameList
	}
	return nil
}

func (m *GetUserInfoReq) GetAppId() int32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

type CommonResp struct {
	BaseResp             *idl.Resp `protobuf:"bytes,1,opt,name=BaseResp,proto3" json:"BaseResp,omitempty"`
	Data                 string    `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CommonResp) Reset()         { *m = CommonResp{} }
func (m *CommonResp) String() string { return proto.CompactTextString(m) }
func (*CommonResp) ProtoMessage()    {}
func (*CommonResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1}
}

func (m *CommonResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResp.Unmarshal(m, b)
}
func (m *CommonResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResp.Marshal(b, m, deterministic)
}
func (m *CommonResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResp.Merge(m, src)
}
func (m *CommonResp) XXX_Size() int {
	return xxx_messageInfo_CommonResp.Size(m)
}
func (m *CommonResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResp.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResp proto.InternalMessageInfo

func (m *CommonResp) GetBaseResp() *idl.Resp {
	if m != nil {
		return m.BaseResp
	}
	return nil
}

func (m *CommonResp) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type CreateUserReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=Gender,proto3" json:"Gender,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,4,opt,name=AvatarUrl,proto3" json:"AvatarUrl,omitempty"`
	UserType             int64    `protobuf:"varint,5,opt,name=UserType,proto3" json:"UserType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{2}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateUserReq) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *CreateUserReq) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *CreateUserReq) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *CreateUserReq) GetUserType() int64 {
	if m != nil {
		return m.UserType
	}
	return 0
}

func init() {
	proto.RegisterType((*GetUserInfoReq)(nil), "platform.user.srv.info.GetUserInfoReq")
	proto.RegisterType((*CommonResp)(nil), "platform.user.srv.info.CommonResp")
	proto.RegisterType((*CreateUserReq)(nil), "platform.user.srv.info.CreateUserReq")
}

func init() { proto.RegisterFile("info.proto", fileDescriptor_f140d5b28dddb141) }

var fileDescriptor_f140d5b28dddb141 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x6a, 0xf3, 0x30,
	0x10, 0x44, 0xf9, 0x23, 0xde, 0x7c, 0x5f, 0x0f, 0xa2, 0x04, 0x11, 0x7a, 0x30, 0x86, 0x06, 0x9f,
	0x74, 0x48, 0x9f, 0x20, 0x4d, 0x21, 0x0d, 0x94, 0x1c, 0x44, 0x43, 0xe9, 0x51, 0x69, 0xd6, 0x60,
	0x1a, 0x5b, 0xaa, 0xa4, 0x06, 0xfa, 0x20, 0x7d, 0x9d, 0x3e, 0x5b, 0x91, 0x6c, 0x1c, 0x07, 0x9a,
	0xd2, 0xdb, 0xce, 0xce, 0xee, 0xec, 0x78, 0x2c, 0x80, 0xbc, 0xcc, 0x14, 0xd7, 0x46, 0x39, 0x45,
	0xc7, 0x7a, 0x2f, 0x5d, 0xa6, 0x4c, 0xc1, 0xdf, 0x2d, 0x1a, 0x6e, 0xcd, 0x81, 0x7b, 0x76, 0x02,
	0x5b, 0x69, 0xb1, 0x9a, 0x49, 0xb6, 0x70, 0xb1, 0x44, 0xb7, 0xb1, 0x68, 0x56, 0x65, 0xa6, 0x04,
	0xbe, 0xd1, 0x31, 0x0c, 0x02, 0xdc, 0x31, 0x12, 0x93, 0xb4, 0x2b, 0x6a, 0x44, 0x13, 0xf8, 0x37,
	0x77, 0xce, 0xac, 0x65, 0x81, 0x0f, 0xb9, 0x75, 0xac, 0x13, 0x77, 0xd3, 0x48, 0x9c, 0xf4, 0xe8,
	0x25, 0xf4, 0xe7, 0x5a, 0xaf, 0x76, 0xac, 0x1b, 0x93, 0xb4, 0x2f, 0x2a, 0x90, 0xdc, 0x03, 0x2c,
	0x54, 0x51, 0xa8, 0x52, 0xa0, 0xd5, 0x74, 0x0a, 0xc3, 0x5b, 0x69, 0xd1, 0xd7, 0xe1, 0xc2, 0x68,
	0x06, 0x3c, 0x18, 0xf2, 0x1d, 0xd1, 0x70, 0x94, 0x42, 0xef, 0x4e, 0x3a, 0xc9, 0x3a, 0x31, 0x49,
	0x23, 0x11, 0xea, 0xe4, 0x93, 0xc0, 0xff, 0x85, 0x41, 0xe9, 0xd0, 0x9b, 0xfa, 0xcd, 0xed, 0x04,
	0x86, 0xeb, 0xfc, 0xe5, 0xd5, 0x3b, 0xab, 0x15, 0x1a, 0xec, 0x77, 0x96, 0x58, 0xee, 0xd0, 0x04,
	0x9b, 0x91, 0xa8, 0x11, 0xbd, 0x82, 0x68, 0x7e, 0x90, 0x4e, 0x9a, 0x8d, 0xd9, 0xb3, 0x5e, 0xa0,
	0x8e, 0x0d, 0xaf, 0xe8, 0xb5, 0x1f, 0x3f, 0x34, 0xb2, 0x7e, 0xb8, 0xd5, 0xe0, 0xd9, 0x17, 0xa9,
	0x48, 0x9f, 0x21, 0x7d, 0x86, 0x51, 0x2b, 0x52, 0x3a, 0xe5, 0x3f, 0xff, 0x06, 0x7e, 0x9a, 0xfb,
	0x24, 0x39, 0x37, 0xd7, 0xca, 0xee, 0x09, 0xe0, 0xf8, 0xf9, 0xf4, 0xfa, 0xec, 0x46, 0x3b, 0xa2,
	0xbf, 0x08, 0x6f, 0x07, 0xe1, 0x35, 0xdc, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x58, 0x3e,
	0x10, 0x3f, 0x02, 0x00, 0x00,
}
