// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: info.proto

/*
Package platform_user_srv_info is a generated protocol buffer package.

It is generated from these files:
	info.proto

It has these top-level messages:
	GetUserInfoReq
	GetUserInfoResp
	CreateUserReq
	CreateUserResp
*/
package platform_user_srv_info

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/dy-platform/user-api-passport/idl"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserInfo service

type UserInfoService interface {
	// 查询用户信息
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...client.CallOption) (*GetUserInfoResp, error)
	// 创建用户
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...client.CallOption) (*CreateUserResp, error)
}

type userInfoService struct {
	c    client.Client
	name string
}

func NewUserInfoService(name string, c client.Client) UserInfoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "platform.user.srv.info"
	}
	return &userInfoService{
		c:    c,
		name: name,
	}
}

func (c *userInfoService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...client.CallOption) (*GetUserInfoResp, error) {
	req := c.c.NewRequest(c.name, "UserInfo.GetUserInfo", in)
	out := new(GetUserInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userInfoService) CreateUser(ctx context.Context, in *CreateUserReq, opts ...client.CallOption) (*CreateUserResp, error) {
	req := c.c.NewRequest(c.name, "UserInfo.CreateUser", in)
	out := new(CreateUserResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserInfo service

type UserInfoHandler interface {
	// 查询用户信息
	GetUserInfo(context.Context, *GetUserInfoReq, *GetUserInfoResp) error
	// 创建用户
	CreateUser(context.Context, *CreateUserReq, *CreateUserResp) error
}

func RegisterUserInfoHandler(s server.Server, hdlr UserInfoHandler, opts ...server.HandlerOption) error {
	type userInfo interface {
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, out *GetUserInfoResp) error
		CreateUser(ctx context.Context, in *CreateUserReq, out *CreateUserResp) error
	}
	type UserInfo struct {
		userInfo
	}
	h := &userInfoHandler{hdlr}
	return s.Handle(s.NewHandler(&UserInfo{h}, opts...))
}

type userInfoHandler struct {
	UserInfoHandler
}

func (h *userInfoHandler) GetUserInfo(ctx context.Context, in *GetUserInfoReq, out *GetUserInfoResp) error {
	return h.UserInfoHandler.GetUserInfo(ctx, in, out)
}

func (h *userInfoHandler) CreateUser(ctx context.Context, in *CreateUserReq, out *CreateUserResp) error {
	return h.UserInfoHandler.CreateUser(ctx, in, out)
}
